package game.template.logic;

public enum CellType {
    USER_TANK,
    MOBILE_COMPUTER_TANK,
    IMMBOBILE_COMPUTER_TANK,
    TREASURE,
    EMPTY,
    NON_BREAKABLE_BLOCK,
    BREAKABLE_BLOCK,
    BULLET_MOVING_THROUGH
}
